setwd("/data/School/Research/LLM-Elements/Chapter-2")

run_script <- function(path) {
  cat("\n========================================\n")
  cat("STARTING:", path, "\n")
  cat("Time:", format(Sys.time()), "\n")
  cat("========================================\n")
  source(path, local = FALSE)
  cat("\n[DONE]:", path, "at", format(Sys.time()), "\n")
}

run_script("Code/01 - Setup.R")
run_script("Code/02b - Helper functions.R")
run_script("Code/00 - Structured output.R")
run_script("Code/02 - Single respondent.R")
run_script("Code/03a - Multiple issues.R")
run_script("Code/03b - Expanding sample.R")
run_script("Code/04 - Individual accuracy.R")
run_script("Code/04b - Party PRE.R")
run_script("Code/05 - Aggregate accuracy.R")
run_script("Code/06 - Confidence filtering.R")
run_script("Code/07 - Party subgroups.R")
run_script("Code/07b - Rare profiles.R")
run_script("Code/07c - Heatmap.R")
run_script("Code/08a - Regression comparison.R")
run_script("Code/08b - Regression plot.R")
run_script("Code/09a - Ideal points.R")
run_script("Code/09b - Ideal point plot.R")
run_script("Code/10 - Ideal point comparison.R")
run_script("Code/11 - Polarization inflation.R")

cat("\n\n========================================\n")
cat("ALL SCRIPTS COMPLETE at", format(Sys.time()), "\n")
cat("========================================\n")
